---
title: "ANTsR try with our data"
output: html_notebook
---


```{r}
library(ANTsR)
library(dplyr)
```

## Define functions for plotting
```{r}

# Only one image
antsplot.single <- function(image, axis=1, step=10){
  invisible(
    plot(
      image,
      axis=axis,
      # slices=seq(90, 160, by=step),
      doCropping = F
    )  
  )
}


# Simple overlay with alpha
antsplot.olay <- function(bg, olay, axis=1, alpha=0.5){
  invisible(
    plot(
      bg, olay,
      axis=axis,
      color.overlay='red',
      doCropping = T,
      alpha=alpha,
      window.overlay = quantile(olay, c(0.72,1))
    )  
  )
}


# Overlay canny borders
antsplot.canny <- function(bg, olay, axis=1, alpha=1, step=10){
  canned_olay = iMath(olay, "Canny", 20,20,20)
  invisible(
    plot(
      bg, canned_olay,
      axis=axis,
      # slices=seq(90, 160, by=step),
      color.overlay='red',
      doCropping = F,
      alpha=alpha
    )  
  )
}

```


## Load the data
```{r}
bd='/data00/leonardo/layers/regdata/'

full_filename <- paste0(bd,'sub_02/ses_01/anat/full_T1w_bc_brain.nii.gz')
part_filename <- paste0(bd,'sub_02/ses_01/anat/part_T1w_bc_brain.nii.gz')
fmri_filename <- paste0(bd,'sub_02/ses_01/func/task_1_run_1_mean_bc_brain.nii.gz')

```


```{r}
full <- antsImageRead(full_filename)
part <- antsImageRead(part_filename)
fmri <- antsImageRead(fmri_filename)

antsplot.single(full, axis = 1)
antsplot.single(part, axis = 1)
antsplot.single(fmri, axis = 1)

antsplot.canny(fmri,part,axis = 1)

antsplot.olay(fmri,part)

```

## Register fmri to part
```{r}

fmri2part <- antsRegistration(
  fixed = part,
  moving = fmri,
  typeofTransform = "Affine",   # Affine or SyNBoldAff
  verbose = F
)

antsplot.canny(fmri2part$warpedmovout, part)

fmri2part.filename <-  gsub(".nii.gz", "_reg2part.nii.gz", fmri_filename)

antsImageWrite(fmri2part$warpedmovout, fmri2part.filename)


```


## Register part to full
```{r}

part2full <- antsRegistration(
  fixed = full,
  moving = part,
  typeofTransform = "Affine",
  verbose = F
)

antsplot.canny(part2full$warpedmovout, full)

part2full.filename <-  gsub(".nii.gz", "_reg2full.nii.gz", part_filename)
antsImageWrite(part2full$warpedmovout, part2full.filename)

```



## Register part to full with initial translation
```{r}
part2full_translation <- antsRegistration(
  fixed = full,
  moving = part,
  typeofTransform = "Translation",
  verbose = F
)

antsplot.canny(part2full_translation$warpedmovout, full)


part2full <- antsRegistration(
  fixed = full,
  moving = part,
  typeofTransform = "Affine",
  initialTransform = part2full_translation$fwd,
  verbose = F
)

antsplot.canny(part2full$warpedmovout, full)

part2full.filename <-  gsub(".nii.gz", "_reg2full.nii.gz", part_filename)
antsImageWrite(part2full$warpedmovout, part2full.filename)

```







## Register func to part_anat
```{r}
Func_2_Panat <- antsRegistration(
  fixed = part_anat,
  moving = func,
  typeofTransform = "SyNBoldAff",
  verbose = F
)

antsplot.canny(
  Func_2_Panat$warpedmovout, part_anat
)

Func_2_Panat.filename <-  gsub(".nii.gz", "_reg2partanat.nii.gz", func_filename)

antsImageWrite(Func_2_Panat$warpedmovout, Func_2_Panat.filename)



canned_olay = iMath(func, "Canny", 20,20,20)

antsplot.single(part_anat)

gdilated <- iMath(full_anat, "GD", 2)

antsplot.canny(full_anat, gdilated - full_anat)



antsplot.canny <- function(bg, olay, axis=1, alpha=1, step=10){
  canned_olay = iMath(olay, "Canny", 20,20,20)
  invisible(
    plot(
      bg, canned_olay,
      axis=axis,
      # slices=seq(90, 160, by=step),
      color.overlay='red',
      doCropping = F,
      alpha=alpha
    )  
  )
}





```


```{r}

denoised <- iMath(part_anat, "PeronaMalik", 20, 0.5)

antsplot.single(part_anat)
antsplot.single(denoised)
antsplot.single(part_anat - denoised)

grad <- iMath(denoised, "Grad", 1, 1)
antsplot.single(grad)


canned_olay = iMath(part_anat, "Canny", 10,10,10)
canned_olay_smooth = smoothImage(canned_olay, 1)

antsplot.olay(denoised, canned_olay, alpha = 1)

antsplot.single(
  smoothImage(part_anat,0.5)
)

part_anat %>% 
  smoothImage(1) %>%
  iMath("PeronaMalik", 20, 05) %>%
  iMath("Canny", 5,5,5) %>% 
  antsplot.single()



```













