---
title: "layer specific activity"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r, message=FALSE, echo=FALSE}
library(flexdashboard)
library(shiny)
library(plotly)
library(oro.nifti)
library(neurobase)
library(ANTsR)
library(papayaWidget)
library(magrittr)
library(extrantsr)
library(dplyr)
library(promises)
library(future)
library(kableExtra)

defaultW <- getOption("warn") 
options(warn = -1) 


bd <- "/data00/layerfMRI/Github_repo/layerfMRI/analyses/2D_histogram_MNI"
datadir <- paste0(bd,"/data4histograms")
ROIsdir <- paste0(bd,"/ROIs")

MNI_file <- paste0(datadir,"/icbm152_2009_brain.nii.gz") 
MNI <- MNI_file %>% oro.nifti::readNIfTI()

MNI_masked_file <- paste0(datadir,"/icbm152_2009_brain_MASKED.nii.gz")

Zmotion_file <- paste0(datadir,"/MOTION_thresh_zstat1.nii.gz") 
Zmotion <- Zmotion_file %>% oro.nifti::readNIfTI()

Zscrambled_file <- paste0(datadir,"/SCRAMBLED_thresh_zstat1.nii.gz") 
Zscrambled <- Zscrambled_file %>% oro.nifti::readNIfTI()

depth <- paste0(datadir,"/median_depth.nii.gz") %>% oro.nifti::readNIfTI()
layers <- paste0(datadir,"/median_layers.nii.gz") %>% oro.nifti::readNIfTI()

```



Column {data-width=400}
-------------------------------------
    
### 1D histogram for Motion and Scrambled {data-height=300}
    
```{r, message=FALSE}

renderPlotly({

  Zthr <- input$Zthr

  idx_motion <- which(Zmotion > Zthr)
  idx_scrambled <- which(Zscrambled > Zthr)

  M_density <- density(depth[idx_motion])
  S_density <- density(depth[idx_scrambled])

  plot_ly() %>%
    add_trace(
      x = M_density$x, y = M_density$y,
      type = 'scatter', mode = 'lines', name = 'Motion', fill = 'tozeroy'
    ) %>%
    add_trace(
      x = S_density$x, y = S_density$y,
      type = 'scatter', mode = 'lines', name = 'Scrambled', fill = 'tozeroy'
    )

})

```
   
   
### 2D histogram depth-by-Zstat {data-height=700}
    
```{r, message=FALSE}

plot_2Dhist <- function(Zthr, Zmax, chosenZstat, title) {

  idx <- which(chosenZstat > Zthr & chosenZstat < Zmax)
  x = depth[idx]
  y = chosenZstat[idx]

  p <- plot_ly(
    x = depth[idx],
    y = chosenZstat[idx],
    height = 350, width = 450 
  ) %>%
    add_markers(color = x, colors = "Reds", alpha = 0) %>%
    add_trace(
      type = 'histogram2dcontour',
      colorscale = "Viridis",
      contours = list(showlabels=TRUE)
    ) %>%
    layout(
      title = title,
      xaxis = list(
        title = 'cortical depth'
      ),
      yaxis = list(
        title = 'Z-stat'
      )
    )

  return(p)

}


output$plotMotion2D <- renderPlotly({
  plot_2Dhist(
    Zthr = input$Zthr, Zmax = 8,
    chosenZstat = Zmotion, title = 'Motion'
  )
})


output$plotScrambled2D <- renderPlotly({
  plot_2Dhist(
    Zthr = input$Zthr, Zmax = 8,
    chosenZstat = Zscrambled, title = 'Scrambled'
  )
})



# ------------ UI -------------

# see here:
# https://community.plotly.com/t/plotly-shiny-reactive-height-of-plots/1503/3

htmltools::div(style = "display:inline-block", plotlyOutput("plotMotion2D"))

sliderInput("Zthr", label = "Zthr", min = 2.3, max = 8, value = 3.1, width = "100%")

htmltools::div(style = "display:inline-block", plotlyOutput("plotScrambled2D"))


```
   
   
Column {data-width=600}
-------------------------------------
   
### Table {data-height=300}

```{r}

library(parallel)
library(foreach)
library(doParallel)
recruitedCores <- detectCores() %/% 2
registerDoParallel(recruitedCores)

# function for the standard error
sderr <- function(x) sd(x)/sqrt(length(x))


atlastable <- function(Zcontrast) {
  
  Zthrvol <- Zcontrast

  Zmask <- Zthrvol
  Zmask[Zmask !=0 ] = 1
  
  jubrain <- paste0(datadir,"/atlas_juelich_icbm.nii.gz") %>% readNIfTI()
  julabels <- paste0(datadir,"/labels_juelich.csv") %>% read.csv(.,stringsAsFactors=FALSE)
  julabels$index <- julabels$index + 1
  
  # I multiply a mask of the sig Zthrvol by the jubrain so that I can map the idx of
  # the voxels in Zthrvol for each of the regions inside the atlas
  Zatlas <- Zmask * jubrain
  
  
  # Find the index of the voxel belonging to each atlas region
  # Use one of the following two:
  
  # # (1) sapply version - pretty slow but already better than a normal loop
  # idx <- sapply(julabels$index, function(x) which(Zatlas == x))
  
  # (2) superfast parallel with foreach and %dopar%
  idx <- foreach(i = julabels$index) %dopar% {
    which(Zatlas == i)
  }
  
  # Calculate the stats to put in the table:
  # (1) numba voxels in each region
  julabels$nvox <- sapply(idx, length)
  
  # (2) mean Z value for the voxels in each region
  julabels$Zmean <- sapply(julabels$index, function(x) mean(Zthrvol[idx[x] %>% unlist]) )
  
  # (3) mean depth for the voxels in each region
  julabels$meanDepth <- sapply(julabels$index, function(x) mean(depth[idx[x] %>% unlist]) )
  
  # (4) std of depth
  err <- sd   # can be sderr or sd
  julabels$stdDepth <- sapply(julabels$index, function(x) err(depth[idx[x] %>% unlist]) )
  
  
  # build the table to display
  tbl2display <- julabels %>%
    dplyr::select(-index) %>%
    filter(nvox > 200) %>%
    mutate(across(where(is.numeric), round, 2)) %>%
    arrange(desc(nvox))
  
  return(tbl2display)
  
}

# render the table
tbl2display <- atlastable(Zmotion)
output$table <- renderTable(tbl2display)

# # # render the table using futures
# output$table <- renderTable({
#   future({
#     atlastable(Zmotion)
#   })
# })

# ---------- UI -------------

tableOutput("table")

# htmltools::div(style = "display:inline-block", tableOutput("tbl2display"))

# # alternative clever way to get the numba of voxels in each region.
# # very fast, but unfortunately does not relay the idx...
# a <- hist(Zatlas[Zatlas !=0], breaks = julabels$index)

```   
 

### Barplot {data-height=300}
```{r, message=FALSE}
library(highcharter)
library(tidyr)

Zmotion_atlas <- atlastable(Zmotion)
Zscrambled_atlas <- atlastable(Zscrambled)

df_mean <- full_join(Zmotion_atlas, Zscrambled_atlas, by="name") %>%
  select(name, M_depth = meanDepth.x, S_depth = meanDepth.y)

df_std <- full_join(Zmotion_atlas, Zscrambled_atlas, by="name") %>%
  select(name, M_depth_std = stdDepth.x, S_depth_std = stdDepth.y)

df_mean_long <- tidyr::gather(df_mean, task, meanDepth, M_depth, S_depth, factor_key = TRUE)
df_std_long <- tidyr::gather(df_std, task, stdDepth, M_depth_std, S_depth_std, factor_key = TRUE)

df_long <- df_mean_long
df_long$err <- df_std_long$stdDepth


h <- df_long %>%
  hchart('column', hcaes(x = name, y = meanDepth, group = task)) %>%
  hc_colors(c("salmon","skyblue")) %>%
  hc_add_series(
    df_long, 'errorbar',
    hcaes(
      x=name,
      low = meanDepth - err,
      high = meanDepth + err,
      group = task
    ),
    centerInCategory = TRUE, groupPadding = .68, whiskerLength = 10
  )
  

output$plot_hc <- renderHighchart(h)

# -------- UI ------------
highchartOutput("plot_hc")


```
 
 
 
 
 
 
 
 
### Slices {data-height=400}
    
```{r, message=FALSE}

observe({

  req(input$Zthr)
  req(input$chosenStat)

  Zstat <- antsImageRead(input$chosenStat)
  Zstat[Zstat >= input$Zthr] = input$Zthr

  output$brainimg <- renderImage({

    plot(
      antsImageRead(MNI_masked_file),
      Zstat,
      color.overlay = "red",
      axis = 1,
      window.img = c(50,150),
      window.overlay = c(input$Zthr -1 , input$Zthr + 1),
      alpha = 1,
      nslices = 16, ncol = 4,
      crop = TRUE, quality = 1,
      outname = paste0(getwd(),"/slice.png")
    )

    list(
      src = paste0(getwd(),"/slice.png")
    )
  }, deleteFile = TRUE)

})


# --------------- UI -------------------

radioButtons("chosenStat", "",
             c("Motion" = Zmotion_file,"Scrambled" = Zscrambled_file),
             inline = TRUE)

imageOutput("brainimg")



```
























